openapi: "3.0.0"
info:
  description: "API that verifies if an email is written politely or not"
  version: "1.0"
  title: "Email politeness evaluator"
  contact:
    email: "simbeliric@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /evaluate:
    post:
      description: "Evaluates if the email is polite or not"

      requestBody:
        description: "Json with single field containing text to evaluate politeness from"
        required: true
        content:
          application/json: {}

      responses:
        '200':
          description: "Returns True if polite False if not"
          content: 
           application/json: {}